services:
  github-runner:
    build: .
    container_name: github-runner
    restart: unless-stopped
    environment:
      - REPO_URL=${REPO_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Optional: Only if you need to run Docker commands
      - runner-work:/home/github-runner/_work    # Named volume for runner work directory

volumes:
  runner-work:
    driver: local 