services:
  github-runner:
    build: .
    container_name: github-runner
    restart: unless-stopped
    environment:
      - REPO_URL=${REPO_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
    volumes:
      - runner-work:/home/github-runner/_work    # Named volume for runner work directory
    user: "1000:1000"  # Use your user's UID:GID

volumes:
  runner-work:
    driver: local 